In [38]:
import paths

import numpy as np
import pandas as pd
import pickle as pk
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [26]:
wm_0 = [file for file in paths.files_mean_vertices_wm if "LR" in file][0::2]
wm_1 = [file for file in paths.files_mean_vertices_wm if "LR" in file][1::2]

gambling_0 = [file for file in paths.files_mean_vertices_gambling if "LR" in file][0::2]
gambling_1 = [file for file in paths.files_mean_vertices_gambling if "LR" in file][1::2]

motor_0 = [file for file in paths.files_mean_vertices_motor if "LR" in file][0::2]
motor_1 = [file for file in paths.files_mean_vertices_motor if "LR" in file][1::2]

language_0 = [file for file in paths.files_mean_vertices_language if "LR" in file][0::2]
language_1 = [file for file in paths.files_mean_vertices_language if "LR" in file][1::2]

social_0 = [file for file in paths.files_mean_vertices_social if "LR" in file][0::2]
social_1 = [file for file in paths.files_mean_vertices_social if "LR" in file][1::2]

relational_0 = [file for file in paths.files_mean_vertices_relational if "LR" in file][0::2]
relational_1 = [file for file in paths.files_mean_vertices_relational if "LR" in file][1::2]

emotion_0 = [file for file in paths.files_mean_vertices_emotion if "LR" in file][0::2]
emotion_1 = [file for file in paths.files_mean_vertices_emotion if "LR" in file][1::2]

In [25]:
def create_Xy(files, y):
    rows = []
    for file in files:
        with open(file, 'rb') as f:
            df = pk.load(f)
        mean_values = df['mean'].values
        rows.append(mean_values)
    X = pd.DataFrame(rows, columns=[f"col_{i+1}" for i in range(379)])
    return X, [y] * len(files)


In [35]:
all_files = [wm_0, wm_1, gambling_0, gambling_1, motor_0, motor_1, language_0, language_1, 
             social_0, social_1, relational_0, relational_1, emotion_0, emotion_1]
classes = [i for i in range(len(all_files))]

X, y = create_Xy(all_files[0], classes[0])
for files, clas in zip(all_files[1:], classes[1:]):
    X_tmp, y_tmp = create_Xy(files, clas)
    X = pd.concat([X, X_tmp], ignore_index=True)
    y = y + y_tmp

In [51]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

y = pd.Series(y)
mask = (X.index % 9 == 0) | (X.index % 10 == 0)

X_test = X[mask]     # строки, где X.index делится на 9 или 10
X_train = X[~mask]   # остальные строки

y_test = y[mask]
y_train = y[~mask]

model = LogisticRegression(random_state=0)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8617086662569146
Confusion Matrix:
 [[105   0   2   2   0   0   0   0   0   0   0   3   0   5]
 [  0 102   2   8   0   0   0   0   0   0   1   4   0   0]
 [  0   0  87   1   4   4   1   0   1   0   4   5   2   6]
 [  1   4   2  89   1   5   0   2   1   0   4   6   1   1]
 [  1   0   4   3  95   1   0   0   0   0   1   2   2   6]
 [  0   0   1   4   0 104   0   0   1   0   0   2   4   1]
 [  1   0   0   0   0   1 113   0   0   0   0   0   0   0]
 [  0   0   1   0   0   0   0 115   0   0   0   0   0   1]
 [  0   0   1   0   1   0   0   0 109   0   0   2   2   0]
 [  1   0   2   0   0   0   0   0   1 113   0   0   0   0]
 [  1   4   8   5   0   2   0   0   1   0  91   3   1   1]
 [  1   2   8   4   2   2   0   0   0   0   2  81   5   9]
 [  0   0   6   3   0   1   0   0   0   0   0   4 103   0]
 [  3   0   5   2   2   0   0   0   1   0   3   3   1  95]]
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.90      0.91   

In [56]:
gambling_0[:3], relational_0[:3]

(['../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/GAMBLING/100206_LR_win.pickle',
  '../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/GAMBLING/100610_LR_win.pickle',
  '../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/GAMBLING/101006_LR_win.pickle'],
 ['../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/RELATIONAL/100206_LR_relation.pickle',
  '../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/RELATIONAL/100610_LR_relation.pickle',
  '../../../HCE_HCP_fMRI_graphs/graphs/vertices/mean/RELATIONAL/101006_LR_relation.pickle'])